language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t mtoledodev/docker-react -f Dockerfile .

script:
    - docker run -e CI=true mtoledodev/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-project"
    env: "DockerReactProject-env"
    bucket_name: "elasticbeanstalk-us-east-2-476036912370"
    bucket_path: "docker-react-project"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY