language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t mtoledodev/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mtoledodev/docker-react npm run test